trigger:
- master
- 3.x

pr:
- master
- 3.x

stages:
- stage: Test
  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true

  jobs:
    - job: test
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: base-template.yml
        - task: UseDotNet@2
          displayName: 'Use .NET Core SDK'
          inputs:
            packageType: sdk
            version: 8.0.300
        - task: DotNetCoreCLI@2
          displayName: 'Test'
          inputs:
            command: custom
            custom: 'cake'
            arguments: --target Test
            workingDirectory: buildsystem
