<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>LibVLCSharp.WinForms.Sample</Title>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>LibVLCSharp.WinForms.Sample</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.16" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LibVLCSharp.WinForms\LibVLCSharp.WinForms.csproj" />
  </ItemGroup>
</Project>